version: "3.3"
services:
  # foundation db / catalog
  fdb:
    # image: foundationdb/foundationdb@sha256:43e6a4e51e181e4ec65161ec57d538196b1b9101c913fccba2867bfc480acadd
    image: foundationdb/foundationdb:7.1.24
    environment:
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR_PORT: 4550
      FDB_PORT: 4550
    container_name: "${COMPOSE_PROJECT_NAME}_fdb-s3-0"
  tso:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && fdbcli -C /config/fdb.cluster --exec \"configure new single memory\" && tso-server --config-file /config/tso.yml"
    depends_on:
      - fdb
      - minio
      - createbuckets
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    container_name: "${COMPOSE_PROJECT_NAME}_tso-s3-0"
    cap_add:
      - SYS_PTRACE
  resource-manager:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_tso-s3-0:18845 && resource-manager --config-file /config/resource-manager.yml"
    depends_on:
      - tso
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    container_name: "${COMPOSE_PROJECT_NAME}_resource-manager-s3-0"
    cap_add:
      - SYS_PTRACE
  server:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - CI_JOB_NAME=github 
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_resource-manager-s3-0:28989 && clickhouse-server --config-file /config/server.yml"
    depends_on:
      - tso
      - resource-manager
      - minio
    ports:
      - "${CLICKHOUSE_PORT_TCP}:52145"
      - "${CLICKHOUSE_PORT_HTTP}:21557"
    container_name: "${COMPOSE_PROJECT_NAME}_server-s3-0"
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    cap_add:
      - SYS_PTRACE

  worker-write:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_server-s3-0:21557 && VIRTUAL_WAREHOUSE_ID=vw_write WORKER_GROUP_ID=wg_write WORKER_ID=w0 clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    ports:
      - "${CNCH_WRITE_WORKER_PORT_TCP}:52145"
    container_name: "${COMPOSE_PROJECT_NAME}_worker-write-s3-0"
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    cap_add:
      - SYS_PTRACE

  worker-default-0:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_server-s3-0:21557 && VIRTUAL_WAREHOUSE_ID=vw_default WORKER_GROUP_ID=wg_default WORKER_ID=r0 clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: "${COMPOSE_PROJECT_NAME}_worker-default-s3-0"
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    cap_add:
      - SYS_PTRACE

  worker-default-1:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_server-s3-0:21557 && VIRTUAL_WAREHOUSE_ID=vw_default WORKER_GROUP_ID=wg_default WORKER_ID=r1 clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: "${COMPOSE_PROJECT_NAME}_worker-default-s3-1"
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    cap_add:
      - SYS_PTRACE

  daemon-manager:
    # image: byconity/debian@sha256:164fd2218d3fb56bc911dcf0e086577d40c3a896126dd7ef81da39d5c97a46a3
    image: byconity/debian:buster-runit-fdb7.1.27
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: bash -c "export PATH=$PATH:/opt/byconity/bin/ && curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 ${COMPOSE_PROJECT_NAME}_server-s3-0:21557 && daemon-manager --config-file ./config/daemon-manager.yml"
    depends_on:
      - server
    container_name: "${COMPOSE_PROJECT_NAME}_daemon-manager-s3-0"
    volumes:
      - binary_volume:/opt/byconity/bin/
      - config_volume_for_s3:/config/
    cap_add:
      - SYS_PTRACE
  minio:
    ports:
      - 19001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

    # origin image: quay.io/minio/minio:RELEASE.2024-01-11T07-46-16Z
    # image: minio/minio@sha256:796f75ea413b883cec953cb5f0bd2b6050615e36123f36e39aa5555096a07bc1
    # image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    image: quay.io/minio/minio:RELEASE.2024-01-11T07-46-16Z
    volumes:
      - /data
    command: server /data --console-address ":9001"
  # Create a default bucket.
  createbuckets:
    # image: minio/mc@sha256:026ae522febcbf07bdc049da5a754cb68773ac4f7f9c02e6d4a99456c72f4a31
    image: minio/mc:RELEASE.2024-01-11T05-49-32Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 minio minio123; /usr/bin/mc mb myminio/part-tools; /usr/bin/mc policy set public myminio/part-tools; /usr/bin/mc mb myminio/cnch; /usr/bin/mc policy set public myminio/cnch; exit 0; "

volumes:
    config_volume_for_s3:
      name: "${CONFIG_VOL_FOR_S3}"
      external: true
    binary_volume:
      name: "${BINARY_VOL}"
      external: true
