logger:
  level: trace
  log: /var/byconity/log/out.log
  errorlog: /var/byconity/log/err.log
  testlog: /var/byconity/test.log
  size: 1000M
  count: 10
path: /var/byconity/
timezone: UTC
daemon_manager:
  port: 17553
  daemon_jobs:
    job:
    -
      name: PART_GC
      interval: 10000
      disable: 0
    -
      name: PART_MERGE
      interval: 10000
      disable: 0
    -
      name: CONSUMER
      interval: 10000
      disable: 0
    -
      name: GLOBAL_GC
      interval: 5000
      disable: 0
    -
      name: PART_CLUSTERING
      interval: 30000
      disable: 0
    -
      name: DEDUP_WORKER
      interval: 3000
      disable: 0

hdfs_addr: "hdfs://COMPOSE_PROJECT_NAME-hdfs-namenode:9000"
storage_configuration:
  disks:
    hdfs_disk:
      path: /user/clickhouse/
      type: bytehdfs
    local_disk:
      path: /var/byconity/data/
      type: local
  policies:
    default:
      volumes:
        local:
          default: local_disk
          disk: local_disk
    cnch_default_hdfs:
      volumes:
        hdfs:
          default: hdfs_disk
          disk: hdfs_disk
cnch_config: /config/cnch-config.yml
