logger:
  level: trace
  log: /var/log/byconity/out.log
  errorlog: /var/log/byconity/err.log
  testlog: /var/log/byconity/test.log
  size: 1000M
  count: 10
http_port: 21557
rpc_port: 30605
tcp_port: 52145
ha_tcp_port: 26247
exchange_port: 47447
exchange_status_port: 60611
interserver_http_port: 30491
mysql_port: 9004
listen_host: "0.0.0.0"
prometheus:
  endpoint: "/metrics"
  port: 0
  metrics: true
  events: true
  asynchronous_metrics: true
  part_metrics: false
cnch_type: server
max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 200
uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120
path: /var/byconity/
tmp_path: /var/byconity/tmp_data/
users_config: /config/users.yml
default_profile: default
default_database: default
timezone: Europe/Moscow
mlock_executable: false
macros:
  "-incl": macros
  "-optional": true
builtin_dictionaries_reload_interval: 3600
max_session_timeout: 3600
default_session_timeout: 60
dictionaries_config: "*_dictionary.xml"
format_schema_path: /var/byconity/format_schemas/
perQuery: 1
storage_configuration:
  disks:
    hdfs_disk:
      path: /user/clickhouse/
      type: bytehdfs
    local_disk:
      path: /var/byconity/data/
      type: local
  policies:
    default:
      volumes:
        local:
          default: local_disk
          disk: local_disk
    cnch_default_hdfs:
      volumes:
        hdfs:
          default: hdfs_disk
          disk: hdfs_disk
cnch_unique_table_log:
  database: cnch_system
  table: cnch_unique_table_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
cnch_kafka_log:
  database: cnch_system
  table: cnch_kafka_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
cnch_query_log:
  database: cnch_system
  table: cnch_query_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
query_log:
  database: system
  table: query_log
  flush_interval_milliseconds: 15000
  partition_by: event_date
part_allocation_algorithm: 1
consistent_hash_ring:
  num_replicas: 16
  num_probes: 21
  load_factor: 1.3
cnch_config: /config/cnch-config.yml
restrict_tenanted_users_to_whitelist_settings: false
restrict_tenanted_users_to_privileged_operations: false
sensitive_permission_tenants: 1234
custom_settings_prefixes: SQL_
