profiles:
  default:
    load_balancing: random
    log_queries: 1
    max_execution_time: 180
    exchange_timeout_ms: 300000
  readonly:
    readonly: 1

users:
  default:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
    access_management: 1
  readonly:
    networks:
      ip: ::/0
    password: ""
    profile: readonly
    quota: default
    access_management: 1
  server:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
    access_management: 1
  probe:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
    access_management: 1

quotas:
  default:
    interval:
      duration: 3600
      queries: 0
      errors: 0
      result_rows: 0
      read_rows: 0
      execution_time: 0