logger:
  level: trace
  log: /var/byconity/out.log
  errorlog: /var/byconity/err.log
  testlog: /var/byconity/test.log
  size: 1000M
  count: 10
  console: true
http_port: 21557
rpc_port: 30605
tcp_port: 52145
ha_tcp_port: 26247
exchange_port: 47447
exchange_status_port: 60611
interserver_http_port: 30491
listen_host: "0.0.0.0"
prometheus:
  endpoint: "/metrics"
  port: 0
  metrics: true
  events: true
  asynchronous_metrics: true
  part_metrics: false
cnch_type: server
max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 100
uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120
path: /var/byconity/
tmp_path: /var/byconity/tmp_data/
users_config: /config/users.yml
default_profile: default
default_database: default
timezone: Asia/Shanghai
mlock_executable: false
macros:
  "-incl": macros
  "-optional": true
builtin_dictionaries_reload_interval: 3600
max_session_timeout: 3600
default_session_timeout: 60
dictionaries_config: "*_dictionary.xml"
format_schema_path: /var/byconity/format_schemas/
service_discovery:
  mode: local
  cluster: default
  disable_cache: false
  cache_timeout: 5
  server:
    psm: data.cnch.server
    node:
      host: server-0
      hostname: server-0
      ports:
        port:
        -
          name: PORT2
          value: 21557
        -
          name: PORT1
          value: 30605
        -
          name: PORT0
          value: 52145
        -
          name: PORT4
          value: 27651
        -
          name: PORT3
          value: 45443
        -
          name: PORT5
          value: 47447
        -
          name: PORT6
          value: 60611
    
  resource_manager:
    psm: data.cnch.resource_manager
    node:
      host: resource-manager-0
      hostname: resource-manager-0
      ports:
        port:
          name: PORT0
          value: 28989
  daemon_manager:
    psm: data.cnch.daemon_manager
    node:
      host: daemon-manager-0
      hostname: daemon-manager-0
      ports:
        port:
          name: PORT0
          value: 17553
  tso:
    psm: data.cnch.tso
    node:
      host: tso-0
      hostname: tso-0
      ports:
        port:
        -
          name: PORT0
          value: 18845
        -
          name: PORT2
          value: 9181
catalog:
  name_space: default
perQuery: 1
catalog_service:
  type: fdb
  fdb:
    cluster_file: /config/fdb.cluster
storage_configuration:
  disks:
    hdfs_disk:
      path: /user/clickhouse/
      type: bytehdfs
    local_disk:
      path: /var/byconity/data/
      type: local
  policies:
    default:
      volumes:
        hdfs:
          default: hdfs_disk
          disk: hdfs_disk
        local:
          default: local_disk
          disk: local_disk
hdfs_addr: "hdfs://hdfs-namenode:9000"
merge_tree:
  old_parts_lifetime: 0
  ttl_for_trash_items: 30
cnch_kafka_log:
  database: cnch_system
  table: cnch_kafka_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
query_log:
  database: system
  table: query_log
  flush_interval_milliseconds: 10000
  partition_by: event_date
server_part_log:
  database: system
  table: server_part_log
  flush_interval_milliseconds: 10000
  partition_by: event_date
part_merge_log:
  database: system
  table: part_merge_log
  flush_interval_milliseconds: 10000
  partition_by: event_date
part_allocation_algorithm: 1
consistent_hash_ring:
  num_replicas: 16
  num_probes: 21
  load_factor: 1.3
cnch_config: "/config/cnch-config.yml"
restrict_tenanted_users_to_whitelist_settings: false
restrict_tenanted_users_to_privileged_operations: false
sensitive_permission_tenants: 1234
